### PR TITLE
sort_index was deprecated in pandas 0.17. Make its use conditional.

### PR DESCRIPTION
**Pull request by robottwo**
This patch gets rid of the "deprecated" warning when using Pandas
versions newer than 0.17 (vs the last patch), but also makes pyjstat
compatible with versions of Pandas < 0.17.

### CODE REVIEW

**Comment by maxsap** [comment]
I think this also resolved the issue I have reported https://github.com/predicador37/pyjstat/issues/29

Any reason it has not been merged?

**Comment by janbrus** [comment]
It is important to get this fixed as pyjstat is not workin with pandas >=1.0.0. It is the argument by that is not working. 
An alternative is still to use sort_index() but remove by='index' 
dim_label = pd.merge(dim_label, dim_index, on='id').sort_index()
see: [Pandas doc sort_index](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_index.html)

**Comment by predicador37** [comment]
Hi guys! Sorry for my being out of business; I'll try to keep an eye on these issues more frequently.
I don't think the use of conditionals to check for pandas version is a good practice. I think the best for pyjstat is just to support the latest releases of pandas.

I'll try to release a version in a few hours.

**Comment by predicador37** [comment]
OK, so a new pyjstat version has been released, which is only compatible with Pandas 1.X and Python 3.X versions. I think this is the way to go, since support for Python 2.7 has already ended.

Thanks for your PR, but I think it won't be necessary.

**Pull request closed without merging**
