### PR TITLE
Fix KeyError for empty values in get_values()

### PR DESCRIPTION
**Pull request by coriemiller**
Pesky ONS data! Was getting a KeyError using the following dataset

URL = http://web.ons.gov.uk/ons/api/data/dataset/CPI15.json?context=Economic&jsontype=json-stat&apikey={YOUR_API_KEY}&geog=2011STATH&diff=&totals=false

### CODE REVIEW

**Comment by predicador37** [comment]
Hi, @coriemiller :

I'm not getting any error parsing that dataset. Could you paste some code?

Thanks

**Comment by coriemiller** [comment]
Sure thing- running the code below resulted in a KeyError.

```
from pyjstat import pyjstat
import requests
from collections import OrderedDict

url = 'http://web.ons.gov.uk/ons/api/data/dataset/CPI15.json?context=Economic&jsontype=json-stat&apikey={YOUR_API_KEY}&geog=2011STATH&diff=&totals=false'
data = requests.get(url)
results = pyjstat.from_json_stat(data.json(object_pairs_hook=OrderedDict))
results[0].to_csv('cpi_output.csv')
```

Error:
```
Traceback (most recent call last):
  File "/Users/cmiller/GoogleDrive/local/kettle/etl/ons/api_to_csv.py", line 9, in <module>
    results = pyjstat.from_json_stat(data.json(object_pairs_hook=OrderedDict))
  File "/Users/cmiller/GoogleDrive/local/kettle/etl/ons/ons/lib/python2.7/site-packages/pyjstat/pyjstat.py", line 355, in from_json_stat
    results.append(generate_df(js_dict, naming, value))
  File "/Users/cmiller/GoogleDrive/local/kettle/etl/ons/ons/lib/python2.7/site-packages/pyjstat/pyjstat.py", line 314, in generate_df
    values = get_values(js_dict, value=value)
  File "/Users/cmiller/GoogleDrive/local/kettle/etl/ons/ons/lib/python2.7/site-packages/pyjstat/pyjstat.py", line 236, in get_values
    if values[i]:
KeyError: 31496
```

**Comment by TheResurrectionOfLight** [comment]
Experiencing similar issues with another dataset- I think something strange happens in the get_values function when values are null or missing. 

URL = http://web.ons.gov.uk/ons/api/data/dataset/JOBS2.json?context=Economic&jsontype=json-stat&apikey={YOUR_API_KEY}&geog=2011STATH&diff=Q22016&totals=false

Notice the empty values for certain filters 
(data explorer: http://web.ons.gov.uk/ons/data/dataset-finder/-/q/datasetView/Economic/JOBS2?p_auth=hXbdVPy2&p_p_auth=2thZcr41&p_p_lifecycle=1&_FOFlow1_WAR_FOFlow1portlet_geoTypeId=2011STATH&_FOFlow1_WAR_FOFlow1portlet_diff=Q22016&_FOFlow1_WAR_FOFlow1portlet_UUID=0)

screenshot at oct 10 15-27-03

With the fix above, the dataset gets parsed to a dataframe, but dimensions get shifted incorrectly. Without the fix, we get the following keyerror
```
Traceback (most recent call last):
  File "/Users/cmiller/GoogleDrive/local/kettle/etl/ons/api_to_csv.py", line 13, in <module>
    results = pyjstat.from_json_stat(data.json(object_pairs_hook=OrderedDict))
  File "/Users/cmiller/GoogleDrive/local/kettle/etl/ons/ons/lib/python2.7/site-packages/pyjstat/pyjstat.py", line 359, in from_json_stat
    results.append(generate_df(js_dict, naming, value))
  File "/Users/cmiller/GoogleDrive/local/kettle/etl/ons/ons/lib/python2.7/site-packages/pyjstat/pyjstat.py", line 315, in generate_df
    values = get_values(js_dict, value=value)
  File "/Users/cmiller/GoogleDrive/local/kettle/etl/ons/ons/lib/python2.7/site-packages/pyjstat/pyjstat.py", line 236, in get_values
    if values[i]:
KeyError: 3366
```
Either my fix isn't truly solving the issue, or in another function down the line something gets shifted or does something funky with empty values. Let me know if I can send over more information to help debug!

**Comment by predicador37** [comment]
I hope I can study this the next days. Sorry for the inconvenience and
thanks for your help and patience!

**Comment by coriemiller** [comment]
No problem- thanks for looking into it!

**Comment by predicador37** [comment]
Hi, @coriemiller :

Sorry for my delay. It was easier than that... I've refactored three lines of code and now the bug should be fixed. This was another big one, should have tested it better...

Please, tell me if it works. Thanks again for your help!

**Comment by coriemiller** [comment]
I tested it on my datasets- it works for me! Thanks so much for the fix.

**Comment by predicador37** [comment]
Great! I'm going to close this thread. Finally your pull request wasn't neccessary, but I appreciate a lot your help. Every pyjstat user contributes to make a better pyjstat!

**Comment by coriemiller** [comment]
Trying to install version 0.3.5 with pip - looks like it still has 0.3.4- just wanted to give you a heads up!

**Comment by predicador37** [comment]
Thanks a lot again, @coriemiller. It was late here when I uploaded the patch to Github; it seems I forgot to execute the dist-upload command. Last version should be in pip right now (I've had some problems with my Internet connection these days, could have uploaded it earlier).

**Pull request closed without merging**
